apiVersion: v2
type: application
name: gatekeeper-policy-manager
description:
  A Helm chart for Gatekeeper Policy Manager, a simple to use, read-only web UI for
  viewing OPA Gatekeeper policies' status in a Kubernetes Cluster.
home: https://sighup.io
sources:
  - https://github.com/sighupio/gatekeeper-policy-manager/
icon: https://raw.githubusercontent.com/sighupio/gatekeeper-policy-manager/master/app/static-content/logo.svg
maintainers:
  - name: Ramiro Algozino
    email: ramiro@sighup.io
  - name: Alessio Pragliola
    email: alessio.pragliola@sighup.io
keywords:
  ["opa", "gatekeeper", "policy", "ui", "dashboard", "web", "rego", "webapp"]

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "0.8.0"

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "v1.0.8"
