apiVersion: v1
entries:
  gatekeeper-policy-manager:
  - apiVersion: v2
    appVersion: v1.0.5
    created: "2023-07-26T14:14:40.585940889-04:00"
    description: A Helm chart for Gatekeeper Policy Manager, a simple to use, read-only
      web UI for viewing OPA Gatekeeper policies' status in a Kubernetes Cluster.
    digest: 0187d1cbb29d6e39b4f362d325c47a58da59881e0ee46335704467ae39ea47b1
    home: https://sighup.io
    icon: https://raw.githubusercontent.com/sighupio/gatekeeper-policy-manager/master/app/static-content/logo.svg
    keywords:
    - opa
    - gatekeeper
    - policy
    - ui
    - dashboard
    - web
    - rego
    - webapp
    maintainers:
    - email: ramiro@sighup.io
      name: Ramiro Algozino
    - email: alessio.pragliola@sighup.io
      name: Alessio Pragliola
    name: gatekeeper-policy-manager
    sources:
    - https://github.com/sighupio/gatekeeper-policy-manager/
    type: application
    urls:
    - https://markieta.com/gatekeeper-policy-manager/gatekeeper-policy-manager-0.4.3.tgz
    version: 0.4.3
generated: "2023-07-26T14:14:40.584785644-04:00"
